### ISSUE TITLE
Stylesheets not imported?

### ISSUE THREAD

**Issue by mattyg** [Holo-Host/web-sdk#103]
It seems like maybe some styling is not included in the login UI as intended?

For example, if I set an image, the image is not centered, but I see there is a css class `img-center` that doesn't have any rules specified.

I would also like to see the buttons / links more clearly visually distinguished. For example, the "login here" button is not distinct from its surrounding text.

**Comment by mattyg** [comment]
i deleted node_modules and reinstalled --- seemed to import the stylesheet now

**Comment by mattyg** [comment]
Seems like when I install via the git repo the stylesheets are there, but when I install from the npm package they're imported but empty.

**Comment by robbiecarlton** [comment]
@mattyg - any chance you can send me a reproduction (ideally minimal) of this? I'm not seeing it, all styles are appearing as expected

**Comment by mattyg** [comment]
> @mattyg - any chance you can send me a reproduction (ideally minimal) of this? I'm not seeing it, all styles are appearing as expected

Seems resolved -- I can't reproduce it anymore either.
