### ISSUE TITLE
connect() never resolves Promise -- possibly due to thrown error?

### ISSUE THREAD

**Issue by mattyg** [Holo-Host/web-sdk#99]
It seems like calling `await WebSdkApi.connect(..)` never resolves the promise, even though it's logging to the console that the app is installed and running. 

I'm working off this branch (https://github.com/mattyg/web-sdk/tree/holochain-v0.2-build-on-install), which merges develop, PR #96 and PR #94.

I always get this error in console once, before the success messages below. It's thrown from this line: https://github.com/Holo-Host/web-sdk/blob/737d11e672eb5f6e306ec7b864898b53d9d76bf9/src/index.ts#L15C1-L15C1
```
Uncaught (in promise) TypeError: t3 is undefined
```

It logs this to the console every few seconds:
```
08:29:11.774 EnvoyApi: Getting app status [bundle.js:2:273498](http://127.0.0.1:24274/build/bundle.js)
08:29:11.777 app_status 
Object { type: "installed", data: {…} }
[bundle.js:2:281501](http://127.0.0.1:24274/build/bundle.js)
08:29:11.778 installed app status 
Object { cell_info: {…}, status: "running", enable_errors: [], agent_pub_key: Uint8Array(39), manifest: {…} }
[bundle.js:2:281891](http://127.0.0.1:24274/build/bundle.js)
```

Here's my connect code: 
```
    const client = await WebSdkApi.connect({
      chaperoneUrl: import.meta.env.VITE_CHAPERONE_SERVER_URL
        ? import.meta.env.VITE_CHAPERONE_SERVER_URL
        : "http://localhost:24274",
      authFormCustomization: {
        logoUrl: "assets/cat-eating-bird-circle.png",
        appName: "MewsFeed",
        requireRegistrationCode: false,
      },
    });

    console.log("holo connected", client);    
```

**Comment by robbiecarlton** [comment]
Hey @mattyg - this is most likely due to a version mismatch between chaperone and web-sdk. There's now better reporting for this kind of version mismatching, but I don't think it's in your version of hds. I'm going to get you a new version of web-sdk and hds and see if that resolves the issue.

If not we can take it from there

**Comment by mattyg** [comment]
Yep that resolved it- thank you!!
